### ISSUE TITLE
make release tags

### ISSUE THREAD

**Issue by xflywind** [status-im/nim-chronos#159]
Please make release tags, otherwise it is more likely to break Nim CI which always requests latest chronos version)

Ref https://github.com/status-im/nim-chronos/commit/d595e0dbc63c56807de9690d67c00b979f6404ca

https://github.com/nim-lang/Nim/issues/17130

Thanks!

**Comment by timotheecour** [comment]
> Nim CI which always requests latest chronos version

see `useHead ` https://github.com/nim-lang/Nim/pull/17131#issuecomment-782808213

**Comment by arnetheduck** [comment]
> latest chronos version

I'm not sure why this makes any difference? chronos tests with `master` are green with Nim in the chronos repo - ie every chronos master commit is as good as a release tag.

**Comment by xflywind** [comment]
Not always, I guess?

![image](https://user-images.githubusercontent.com/43030857/111649542-6d1f0a00-883f-11eb-9457-9df80dd5665b.png)

**Comment by arnetheduck** [comment]
Github actions is broken for i386 currently, upstream issues, causing partial failures - having a release tag unfortunately wouldn't resolve that.

See https://github.com/actions/virtual-environments/issues/2951#issuecomment-801086425

![Screenshot from 2021-03-18 16-52-47](https://user-images.githubusercontent.com/1382986/111656000-6924c500-880a-11eb-8065-9a8897a1d652.png)

**Comment by xflywind** [comment]
OK, thanks

**Comment by arnetheduck** [comment]
I suspect making release tags isn't really a problem, just don't think they will help with this particular situation.

**Comment by xflywind** [comment]
This shows another failed case

https://github.com/nim-lang/Nim/pull/17495

https://github.com/nim-lang/Nim/pull/17495/checks?check_run_id=2182688051


```
  PASS: [3/42] chroma c                                                     ( 4.13 sec)
  FAIL: chronicles c
  Test "chronicles" in category "nimble-packages"
  Failure: reBuildFailed
  nim c -o:chr -r chronicles.nim
  Hint: used config file '/Users/runner/work/Nim/Nim/config/nim.cfg' [Conf]
  Hint: used config file '/Users/runner/work/Nim/Nim/config/config.nims' [Conf]
  Hint: used config file '/Users/runner/work/Nim/Nim/pkgstemp/chronicles/nim.cfg' [Conf]
  ......................................................
  /Users/runner/.nimble/pkgs/chronos-3.0.0/chronos/asyncmacro2.nim(185, 1) template/generic instantiation from here
  /Users/runner/.nimble/pkgs/chronos-3.0.0/chronos/asyncmacro2.nim(187, 55) Error: can raise an unlisted exception: ref ValueError
```

**Comment by arnetheduck** [comment]
> This shows another failed case

this is a `chronicles` failure though, as an incompatible chronos change was introduced (hence the new chronos major release number)
