### ISSUE TITLE
closure environment reference count leak on self-referencing closures

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-chronos#160]
```
import chronos

type X = ref object

proc testit123(xxx: X) {.async.} =
  addTimer(Moment.now()) do (p: pointer):
    asyncSpawn testit123(xxx)

discard testit123(X())
while true:
  poll()

```

we can see how there's only one instance of `xxx` and how each testit123 completes and therefore _should_ release its reference to `xxx` - yet the count keeps growing:
```
[arnetheduck@tempus nim-beacon-chain]$ nim c -r -d:loggc "testit.nim" | grep Xxx
...
[GC] incRef: 0x7f15acdb4038 22 Xxx rc=38256; thread=0
[GC] incRef: 0x7f15acdb4038 22 Xxx rc=38257; thread=0
[GC] incRef: 0x7f15acdb4038 22 Xxx rc=38258; thread=0
...
```

this might very well be a transformation issue - the transformation creates a backreference to the "previous" closure environment so these might simply never get released.

**Comment by arnetheduck** [comment]
simplified example:
```
import chronos

type X = ref object

proc testit123(xxx: X) {.async.} =
  callSoon() do (p: pointer):
    discard testit123(xxx)

discard testit123(X())
while true:
  poll()
```

without `async`, there's no refcount leak.

**Comment by sinkingsugar** [comment]
I'm surprised we don't have any tests about memory. That's a scary finding.
Maybe your testing sandbox can be generalized into a proper test to run?

**Comment by cheatfate** [comment]
@sinkingsugar there is no memory leak...

**Comment by arnetheduck** [comment]
@Araq confirms this is expected behaviour and that refcounts will be off in this situation, to effectively be collected by m&s instead
