### ISSUE TITLE
Old versions can't be installed via Nimble.

### ISSUE THREAD

**Issue by kayabaNerve** [status-im/nim-chronos#173]
This repository didn't tag releases, so as far as Nimble is concerned, only `master` exists with version 3.0. Could someone please add tags for 3.0, as well as at least the most recent older releases (I personally am on 2.5.2 just for not having upgraded in a while), for clean integration with Nimble, please? Thank you!

**Comment by arnetheduck** [comment]
The recommended way of using nimble with chronos would be through a commit hash instead - is that possible for you?

**Comment by kayabaNerve** [comment]
Possible? Yes. That said, the lack of ranges greatly increases the risk of conflicting with other Nim projects on the system which also require chronos; hence why I'm asking for proper version utilization.

**Comment by arnetheduck** [comment]
Using versions means nimble no longer gets the most recent commit for the projects we're testing it with, meaning we have to create versions all the time which adds churn, so adding a tag solves one problem and adds another, for the workflow we're generally using.

The recommendation would be that leaf application projects use a commit hash while libraries don't - that means the conflicts don't appear and you get deterministic dependencies in your project, which _generally_ is the right thing to do - this is how you "manually" do lockfiles - at the same time, you ensure that there's a specific version of chronos being used which doesn't break things for your application

**Comment by jlokier** [comment]
Would creating a non-default branch `v2` (not a tag) solve @kayabaNerve's problem without breaking the chronos workflow?

**Comment by kayabaNerve** [comment]
@arnetheduck Thanks for explaining why. I now understand why you aren't doing versioned releases, and can respect that. Happy to drop my request and just use commit hashes.

A branch is the same as a commit, from a Nimble perspective. I also only know so far that the raise effects differ, and I'm not trying to complain about any functionality changes, so I don't need a proper v2 branch (at least, not for now). If I did, since I wouldn't expect backports, a commit hash would still work. Thanks for the suggestion though.

**Comment by arnetheduck** [comment]
>  raise effects differ

the backwards incompatible change is that you must ensure manually added callbacks (using `addCallback` or `addTimer`) don't raise - it was broken before v3, but after v3 it becomes a compile-time error instead of a runtime error.

There's a `strict` mode as well that has slightly stronger requirements, namely that _nothing_ raises `Exception` (`CatchableError` is fine).

**Comment by kayabaNerve** [comment]
Thanks for the heads up! Strict just being available via `-d:strict`?

**Comment by arnetheduck** [comment]
`-d:chronosStrictException`: https://github.com/status-im/nim-chronos/#exception-effects
