### ISSUE TITLE
async not work properly on windows and macOS

### ISSUE THREAD

**Issue by bung87** [status-im/nim-chronos#176]
my test file https://github.com/bung87/scorper/blob/devel/tests/trange.nim  
always fails on windows and macOS, on my local machine macOS runs it will randomly fails, it contains three client request server tests, one of them will get empty body string.

you can check my CI tests here:  
https://github.com/bung87/scorper/actions/runs/714168854  

I also notice CI of nim-chronos on windows and macOS not actually runs.

**Comment by arnetheduck** [comment]
> I also notice CI of nim-chronos on windows and macOS not actually runs.

where do you see this? I can see all of win/mac/linux working here: https://github.com/status-im/nim-chronos/actions/runs/713877718

**Comment by bung87** [comment]
oh , that's maybe the network error , I clicked ` Run nim-chronos tests ` mutiple times, only see one word "Error".

**Comment by cheatfate** [comment]
Sorry but i don't see any relationship between errors in your CI and `nim-chronos`.
https://github.com/bung87/scorper/runs/2259428896?check_suite_focus=true#step:7:212
https://github.com/bung87/scorper/runs/2259428904?check_suite_focus=true#step:7:213

I'm closing this issue, if you still think its relevant please reopen it with some detailed information.

**Comment by bung87** [comment]
please ignore the CI parts, in my case `readExactly` silently fails, stay on writePause state, my client side read nothing. I have no clue why my test case runs fails on windows and macOS randomly but always pass on ubuntu.

**Comment by bung87** [comment]
I found it runs into `readLoop` else branch .
``` nim
if transp.offset == 0:
      # We going to raise an error, only if transport buffer is empty.
      if ReadError in transp.state:
        raise transp.getError()
      else:
```

**Comment by arnetheduck** [comment]
> I found it runs into `readLoop` else branch .

which chronos version is this? there is no `else` like that in `readLoop`

**Comment by bung87** [comment]
I modified it locally for debugging, these's no `else` before,  it's unhandled.

**Comment by cheatfate** [comment]
Fall into case when `transp.offset == 0` and without error is a legal case.
You started `readExactly()` with an empty internal buffer, so at first cycle it will check `transp.offset` and if it zero it starts waiting for data from socket.
And yes it could stuck there forever if there no data available in socket. If remote peer will perform disconnect `readExactly` will raise `TransportIncompleteError` in case when number of bytes read is not equal to number of bytes requested.

**Comment by cheatfate** [comment]
> please ignore the CI parts, in my case `readExactly` silently fails, stay on writePause state, my client side read nothing. I have no clue why my test case runs fails on windows and macOS randomly but always pass on ubuntu.

If your client side reads nothing, maybe your server side do not send anything?

**Comment by bung87** [comment]
it runs into there before my server writing. the async call stack order not constantly , I use single thread , so the reading and writing are mess up

**Comment by cheatfate** [comment]
We all use single thread, but looks like you spawn processes.

**Comment by bung87** [comment]
no idea, it a unit test file I dont mange processes, if something wrong that can't explain why it always passed on Linux.

**Comment by cheatfate** [comment]
@bung87 its very easy to explain, different OS has different TCP/IP networking implementations, different network buffer sizes. So sometimes data could be delivered to your application byte by byte, and sometime it could be delivered in big chunks.

**Comment by bung87** [comment]
do you have idea how to handle this ? I can't think further.
