### ISSUE TITLE
add support sendfile on windows

### ISSUE THREAD

**Issue by bung87** [status-im/nim-chronos#188]
https://github.com/tehmaze/libcommon/blob/master/common/socket/sendfile.c

I found this resource, I have no windows development experience , so am not able create PR for this

**Comment by cheatfate** [comment]
sendfile for Windows is available via https://github.com/status-im/nim-chronos/blob/master/chronos/transports/stream.nim#L2125-L2144

**Comment by bung87** [comment]
I mean https://github.com/status-im/nim-chronos/blob/master/chronos/sendfile.nim , OS level send file.
