### ISSUE TITLE
separate TLSFlags TLSVersion to standalone file or import bearssl when defined ssl

### ISSUE THREAD

**Issue by bung87** [status-im/nim-chronos#190]
https://github.com/status-im/nim-chronos/blob/67f0f1224fe8176cf66c3fc35c74e313906d9658/chronos/streams/tlsstream.nim#L12

`TLSVersion` `TLSFlags`

my proc has params accept TLSVersion TLSFlags also has isSecurity flag, so ssl and non-ssl share same body, I dont want compile bearssl when not defined ssl.

**Comment by cheatfate** [comment]
If you do not want to have SSL bundled, just `import apps/http/httpserver`.

**Comment by bung87** [comment]
well, I use my own http server, I define same data structure solve this  for now.
