### ISSUE TITLE
Future are cyclically referenced in the memory

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-chronos#203]
Nim garbage collect cyclicalled referenced memory less often than regular memory, so having cyclical memory references  causes some spikes in the memory usage on nimbus.

Simple repro:
```nim
proc testAl(): Future[seq[int]] {.async.} =
  return newSeq[int](100000)

proc test2() {.async.} =
  for i in 0..<1000000:
    discard await testAl()

GC_disableMarkAndSweep() # disable cycle collection, leave non cycle collection on
waitFor test2()
```
This will very quickly OOM

```nim
proc testAl(): seq[int] =
  return newSeq[int](100000)

proc test2() =
  for i in 0..<10000000:
    discard testAl()

GC_disableMarkAndSweep() # disable cycle collection, leave non cycle collection on
test2()
```
This works fine and doesn't use more than a few percents of memory

I tried to fiddle a bit with Chronos to fix this, but didn't get any results ATM.

My theory is that the Future is referenced from the iterator, and that the iterator references the Future (through the closure), thus causing a cyclical reference, but maybe @cheatfate will have a better insight

While this is not a critical issue, solving this should both improve ram usage and cpu usage (since cycle collection is costly)

**Comment by cheatfate** [comment]
From what i see this issue present in `asyncdispatch` too. This means that its not bug in the `chronos` features:
* Cancellation mechanism keeps reference to the Future[T] which async procedure is waiting for
* Future[T] tracking is not enabled, Futures are not collected into big linked list.

**Comment by Araq** [comment]
It's not easy to fix, at least for asyncdispatch I easily spent months on this problem. The solution is to use `--gc:orc` which (last time I tested) does work with nim-chronos already. We're fixing it so that it also works with libp2p.
