### ISSUE TITLE
Means to design chronos+asyncdispatch 3rd party libraries

### ISSUE THREAD

**Issue by yglukhov** [status-im/nim-chronos#207]
It is becoming a case that library authors want to support both chronos and asyncdispatch, but currently there's no one way to do it. E.g. an arbitrary library would switch based on `when defined(ChronosAsync)` but other libraries may choose a different flag, which hits usability for the final user, as they'll need to be aware of all of these dependencies and their respective flags. Therefore I suggest to document this flag in chronos README, so that the end user could just add `-d:chronosAsync` and be pretty confident that all dependencies will switch if they can, while library authors should also follow this suggestion and use this flag to switch.

**Comment by arnetheduck** [comment]
One way that we like is to to create separate modules instead of using flags - this allows any framework to live side by side and is less .. global - is that a viable solution in cases like what you're seeing?

https://github.com/status-im/nim-metrics/tree/master/metrics is an example

**Comment by yglukhov** [comment]
It's a viable solution in some cases, but unwieldy in others. E.g. if you look at https://github.com/yglukhov/asyncthreadpool/blob/main/asyncthreadpool.nim you could see there's only one minor difference based on `when defined(ChronosAsync)`, and most of the code is the same for asyncdispatch and chronos. Following your suggestion I would have to move the common code to some private impl file and `include` it from corresponding `chronos_asyncthreadpool` and `asyncdispatch_asyncthreadpool`, which feels unnatural. Moreover, users of `asyncthreadpool` will have to repeat the same pattern despite the interface of `asyncthreadpool` doesn't change for them.

**Comment by arnetheduck** [comment]
ok - wdyt of the `-d:async_backend=[asyncdispatch/chronos]` style? `when async_backend=="chronos"`?

**Comment by yglukhov** [comment]
Sounds good. Anything will do as long as it is documented :)
