### ISSUE TITLE
nim doc doesn't work with nim-chronos

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-chronos#229]
It seems that `asyncdispatch` had a lot of `when defined(nimdoc):` to allow the generation of documentation,
but this has been lost in chronos, and `nim doc chronos.nim` completely fails.

Is this fixable? Since `nim doc` compiles everything, we can't use `nim doc` on libp2p as long as chronos doesn't work (and still exposes the right procs)

**Comment by arnetheduck** [comment]
Duplicate of https://github.com/status-im/nim-chronos/issues/186
