### ISSUE TITLE
Socket operation on non-socket [TransportOsError]

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-chronos#255]
The following runtime error occurs ~~only when used _in the context of a nimble package context_ (with chronos as its only dependency)~~. It has been replicated on:
- macos 10.15.7 (nim v1.2.16, 1.4.6, 1.6.2)
- macos 12.1 (nim v1.2.16, 1.6.2, others not tested)
- ubuntu 20.04 (nim v1.2.16, others not tested)

```shell
/Users/emizzle/repos/emizzle/chronos_stream_error/src/chronos_stream_error.nim(7) chronos_stream_error
/Users/emizzle/.nimble/pkgs/chronos-3.0.11/chronos/asyncloop.nim(1093) waitFor
/Users/emizzle/.nimble/pkgs/chronos-3.0.11/chronos/asyncfutures2.nim(515) read
/Users/emizzle/.nimble/pkgs/chronos-3.0.11/chronos/asyncfutures2.nim(501) internalCheckComplete
Error: unhandled exception: (38) Socket operation on non-socket [TransportOsError]
```
Minimum reproducible code:
```nim
import chronos

let
  (rfd, wfd) = createAsyncPipe()
  transp = fromPipe(wfd)

discard waitFor transp.write("hi")
```
@michaelsbradleyjr and I have narrowed the issue down to sending of bytes in the socket in the `fastWrite` template introduced in https://github.com/status-im/nim-chronos/commit/c25fa1f6cdb2bd604743493e886f0bd9f99a6e2e:
https://github.com/status-im/nim-chronos/blob/17fed89c99beac5a92d3668d0d3e9b0e4ac13936/chronos/transports/stream.nim#L2058

The above snippet **failing** inside of minimal nimble package context:
```shell
git clone https://github.com/emizzle/chronos-stream-error
cd chronos-stream-error
nimble install
nim c -r "./src/chronos_stream_error.nim"
```

~~The above snippet **working** inside of a `nimbus-build-system` context:~~
```shell
git clone https://github.com/emizzle/nim-test-env
cd nim-test-env
make -j16 update && make chronos_stream_error
```

**Comment by arnetheduck** [comment]
> The following runtime error occurs only when used in the context of a nimble package context (with chronos as its only dependency). It has been replicated on:

this is why we don't use nimble - it injects code from random locations and versions into your project, which in turn has a tendency to break things.. every time you use nimble, you need to clear your hidden nimcache folder, but even then it will not work because the dependency resolver is broken.

**Comment by emizzle** [comment]
Clearing `~/.nimble/pkgs` and `nimcache` didn't seem to fix it. Is there any way to see what nimble injects magically?

**Comment by arnetheduck** [comment]
I'm sure there is but I've lost enough many man-hours fighting it to not want to spend more ;) it's a dead end, until lock files.

**Comment by emizzle** [comment]
👍

**Comment by Menduist** [comment]
Sorry but this seem to be a legitimate issue,
https://github.com/status-im/nim-chronos/blob/master/chronos/transports/stream.nim#L358-L380

This part handles the pipes in the regular writing, it's not present in the fast path:
https://github.com/status-im/nim-chronos/blob/master/chronos/transports/stream.nim#L2058

It's actually nimbus-build-system which picked up a wrong dependency in this case, because you have in your vendor directory nim-waku, which uses an old nim-chronos version https://github.com/status-im/nim-chronos/commit/f7dd6b76c2cbf58a8ed755251086067cb67f420e

**Comment by stefantalpalaru** [comment]
> It's actually nimbus-build-system which picked up a wrong dependency in this case

You can verify that with: `cat vendor/.nimble/pkgs/nim-chronos-#head/nim-chronos.nimble-link`

And here's the logic: https://github.com/status-im/nimbus-build-system/blob/25a4c270330026442e09f6cddfb7a944da7cfa4b/makefiles/targets.mk#L139-L145

**Comment by stefantalpalaru** [comment]
How about an explicit list of submodules to skip, instead?

**Comment by cheatfate** [comment]
> Sorry but this seem to be a legitimate issue, https://github.com/status-im/nim-chronos/blob/master/chronos/transports/stream.nim#L358-L380 This part handles the pipes in the regular writing, it's not present in the fast path: https://github.com/status-im/nim-chronos/blob/master/chronos/transports/stream.nim#L2058
> 
> It's actually nimbus-build-system which picked up a wrong dependency in this case, because you have in your vendor directory nim-waku, which uses an old nim-chronos version [f7dd6b7](https://github.com/status-im/nim-chronos/commit/f7dd6b76c2cbf58a8ed755251086067cb67f420e)

There is now `fastwrite` on Windows, `fastwrite` right now is only enabled on Posix platforms.

**Comment by Menduist** [comment]
> There is now fastwrite on Windows, fastwrite right now is only enabled on Posix platforms.

Yes, this issue is probably only on posix
Fix is either disable fast path for pipes, or handle pipes in fast path

> How about an explicit list of submodules to skip, instead?

Sure, as long as dependencies can't "sneak" new dependencies silently, I guess

**Comment by michaelsbradleyjr** [comment]
I've create a minimal nimbus-build-system project [nbs-proj-1](https://github.com/michaelsbradleyjr/nbs-proj-1). On its [`chronos-issue-255`](https://github.com/michaelsbradleyjr/nbs-proj-1/tree/chronos-issue-255) branch I've added module [`issues/chronos_255.nim`](https://github.com/michaelsbradleyjr/nbs-proj-1/blob/chronos-issue-255/issues/chronos_255.nim) to demonstrate the runtime error reported in this issue.

The GHA workflow passes on macOS and Linux for nim-chronos commit 7da1f5d4d2c362a89acbb76f89b866be6bda3ba3:
https://github.com/michaelsbradleyjr/nbs-proj-1/actions/runs/1719868565

They fail as reported for the next commit c25fa1f6cdb2bd604743493e886f0bd9f99a6e2e and the latest commit on master 17fed89c99beac5a92d3668d0d3e9b0e4ac13936:
* https://github.com/michaelsbradleyjr/nbs-proj-1/actions/runs/1719874349
* https://github.com/michaelsbradleyjr/nbs-proj-1/actions/runs/1719831551

The workflow is consistently failing on Windows for an unrelated reason: it seems that in an MSYS2 Bash environment on Windows in GHA, the `tee` command can't interact properly with `/dev/tty`. It's not a problem locally on Windows in [Mintty](https://mintty.github.io/).

I've seen similar on Windows+MSYS2 in GHA for processes that assume `/dev/tty` will work normally. @stefantalpalaru maybe there's a slightly different approach that can be used for Windows or in general so `make update` can succeed?

**Comment by stefantalpalaru** [comment]
> The workflow is consistently failing on Windows for an unrelated reason

Yes, but it's the lack of "OVERRIDE=1". The tty error has no consequence.

**Comment by michaelsbradleyjr** [comment]
> Yes, but it's the lack of "OVERRIDE=1". The tty error has no consequence.

When *not* using `OVERRIDE=1` on macOS or Linux locally or in GHA, or Windows+MSYS2 locally, I don't get an error.

So I don't understand why the lack of it in GHA specifically for Windows is a problem. Can you elaborate?

**Comment by stefantalpalaru** [comment]
This should get rid of that tty problem: https://github.com/status-im/nimbus-build-system/commit/f85ad74a0516db1abb8839714cd2330d82eed9fa

As for what triggers the Windows CI failure, run a `make status` before trying to do the update.

**Comment by stefantalpalaru** [comment]
@Menduist, this should fix your submodule selection problem: https://github.com/status-im/nimbus-build-system/pull/37

Documented here: https://github.com/status-im/nimbus-build-system#excluded_nim_packages

**Comment by emizzle** [comment]
Wanted to clarify, as @Menduist pointed out, the build system was a false flag, and this is a legitimate issue.

**Comment by cheatfate** [comment]
@emizzle could you please check https://github.com/status-im/nim-chronos/pull/256 it should fix the issue.
