### ISSUE TITLE
Potential unsafe behaviour when cancelling Future

### ISSUE THREAD

**Issue by KonradStaniec** [status-im/nim-chronos#280]
Consider following simplified scenario:

```
import
  chronos

type SomeResourceWhichNeedToBeReleased = object

proc freeResource(res: SomeResourceWhichNeedToBeReleased): void = discard

proc use(res: SomeResourceWhichNeedToBeReleased): void= discard

proc allocateResource: Future[SomeResourceWhichNeedToBeReleased] = discard

proc someProcWhichUsesResource: Future[void] {.async.} =
  let resource = await allocateResource()
  try:
    resource.use()
  finally:
    resource.freeResource()

proc someProcWhichStartAndCancel() {.async.} =
  let fut = someProcWhichUsesResource()

  fut.cancel()
```

What we have been seeing sporadically in fluffy is the following:

1. When calling `fut.cancel()`, the path with the [child](https://github.com/status-im/nim-chronos/blob/master/chronos/asyncfutures2.nim#L287) was taken where child future is `allocateResource` future (and the parent future is `someProcWhichUsesResource`)
2. But child future have already finished but not yet given control to the corresponding yield statement, so child cancel returns [false](https://github.com/status-im/nim-chronos/blob/master/chronos/asyncfutures2.nim#L284). So before cancel return, only the flag `mustCancel` on cancelled future is set to [true](https://github.com/status-im/nim-chronos/blob/master/chronos/asyncfutures2.nim#L295)
3. In the next eventLoop step control is given to the yield statement in `await allocateResource()` [yield](https://github.com/status-im/nim-chronos/blob/master/chronos/asyncmacro2.nim#L274), as the child future already finished (`allocateResource` future is child of `someProcWhichUsesResource` future ). As this child future already finished and not cancelled, resource was already allocated so to clean it up, call to `freeResource` is needed.
4. But as `mustCancel`  was set to true in point `2` for parent future, `await` actually throws a cancellation [exception](https://github.com/status-im/nim-chronos/blob/master/chronos/asyncmacro2.nim#L287) 
5. So it leads to the situation that there is no way to release resources allocated by `allocateResource` function

So my questions here are:
1. Can `allocateResource` do something to make sure resource will be released in such scenario ?
2. Or maybe it is just a bug and actually `mustCancel` should not be set  `true` in case when child future already finished, so the control will go back to parent future and not exception will be thrown ? (i.e if [this](https://github.com/status-im/nim-chronos/blob/master/chronos/asyncfutures2.nim#L287) return false keep `mustCancel = false`)

**Comment by KonradStaniec** [comment]
Extending above example to workable program:
```
import
  std/random,
  chronos

randomize()

var counter = 0

type SomeResourceWhichNeedToBeReleased = object

proc freeResource(res: SomeResourceWhichNeedToBeReleased): void = 
  dec counter

proc checkCounterFut(): Future[void] {.async.} =
  while true:
    echo "Current counter is " & $counter
    await sleepAsync(milliseconds(1))
    
proc use(res: SomeResourceWhichNeedToBeReleased): int = 5

proc allocateResource: Future[SomeResourceWhichNeedToBeReleased] {.async.} = 
  try:
    inc counter
    await sleepAsync(milliseconds(rand(15..55)))
    return SomeResourceWhichNeedToBeReleased()
  except CancelledError as e:
    dec counter
    raise e

proc someProcWhichUsesResource: Future[void] {.async.} =
  let resource = await allocateResource()
  discard resource.use()
  resource.freeResource()

proc someProcWhichStartAndCancel() {.async.} =
  var queries: seq[Future[void]] = @[
    someProcWhichUsesResource(),
    someProcWhichUsesResource(),
    someProcWhichUsesResource()]

  let query = await one(queries)

  let index = queries.find(query)
  
  queries.del(index)

  for f in queries:
    f.cancel()

let checkFut = checkCounterFut()

for i in 0..999:
  asyncSpawn someProcWhichStartAndCancel()

runForever()

```

In above program, I would expect `counter` to settle on `0` value after every future is finished, but currently on my machine it consistently ends up  around `300` which imo is weird.

Changing futures [code](https://github.com/status-im/nim-chronos/blob/master/chronos/asyncfutures2.nim#L287) to not set `mustCancel = true`  in case of already finished child future make this example to finish with counter equal to `0`.

Do you think it is a bug or maybe I am missing something obvious ?

**Comment by Menduist** [comment]
It's a known issue with no good fix in chronos found yet.
A workaround:

```nim
proc someProcWhichUsesResource: Future[void] {.async.} =
  let resourceFut = allocateResource()
  try:
    let resource = await resourceFut
    resource.use()
  finally:
    if resourceFut.finished():
      resourceFut.get().freeResource()
```

**Comment by cheatfate** [comment]
I would expect that this issue was fixed, at least provided sample is now printing
```
Current counter is 0
```
only on Linux with Nim 1.16.4

@KonradStaniec could you confirm that issue has been fixed?
