### ISSUE TITLE
RFC: Future[T] leak or unattended Future[T] tracking.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronos#31]
Implement scheme which will track create/(complete or fail) of `Future[T]` objects.

In such way developer can find never completed `Future[T]` objects which can lead to memory leaks.

All `Future[T]` objects are identified by string `fromProc` and unique `id`. `fromProc` is passed as argument in `newFuture[T]()`. Unique `id` is maintained inside of `newFuture[T]()` procedure.

### Simple way (release mode).

Maintain 3 counters:
 - Number of created `Future[T]` objects, note that all `Future[T]` objects must be created with newFuture(xxx)() procedures.
 - Number of completed `Future[T]` objects. (`Future[T]` is got completed on `complete()` call).
 - Number of failed `Future[T]` objects. (`Future[T]` is got failed on `fail()` call).

If there no leaking Futures number of created Futures must be equal to the sum of number of completed Futures and number of failed Futures.

### Detailed way (debug mode).

Maintable table which will hold all the created `Future[T]` objects and information about it. This can be `Table[FutureFromProc, Table[FutureID, FutureInfo]]`.

`FutureFromProc` is a string which is representing `fromProc` argument of `newFuture[T]() procedure call.
`FutureID` is integer which representing `Future[T]` unique identifier.
`FutureInfo` is object which holds:
1) `Future[T]` moment of creation (or epoch time).
2) File and line number of creation.

Table elements will be added when the `Future[T]` is created and deleted when the
`Future[T]` got completed or failed.

Provide procedure which will dump all the information from table in convenient way.

**Comment by zah** [comment]
Capturing and carrying around all these string values is a bit expensive btw. I suggest the following optimisation:

We can create a reusable module for capturing "source locations". A good place for it would be `std_shims`.

```nim
type
  SourceLocation* = object
    file*: cstring
    line*: int

proc `$`*(loc: ptr SourceLocation): string =
  result.add loc.file
  result.add ":"
  result.add $loc.line

proc sourceLocationIMPL(file: static string, line: static int): ptr SourceLocation =
  var loc {.global.} = SourceLocation(file: cstring(file), line: line)
  return loc.addr

template getSourceLocation*: ptr SourceLocation =
  sourceLocationIMPL(instantiationInfo(-2).filename, instantiationInfo(-2).line)
```

It's used like this:

```nim
import
  source_locations

type
  Future[T] = object
    createdAt: ptr SourceLocation

proc newFuture(T: type, loc: ptr SourceLocation): Future[T] =
  result.createdAt = loc

template newFuture(T: type): auto =
  newFuture(T, getSourceLocation())

var f = newFuture(int)
echo f.createdAt
```

The main idea is that every usage of `newFuture` effectively allocates a single global variable associated with the line of code where `newFuture` was used. A pointer to this global variable is all that needs to be passed around at run-time to track the origin location. There is no run-time memory allocation, string copying and other more expensive operations.

**Comment by cheatfate** [comment]
@zah its very nice idea, but i don't see any reasons to put this small part of code as dependency `std_shims`.

**Comment by zah** [comment]
The main benefit is that it can be used in other projects as well for similar purposes.

**Comment by cheatfate** [comment]
With recent nimble problems i wish to avoid external dependencies, also i dont think 13LOCs deserve its own module name.

**Comment by arnetheduck** [comment]
could this be a finalizer for the future type? ie assert on future that's released without being actioned?

**Comment by cheatfate** [comment]
@arnetheduck you mean with being `read()`?

**Comment by arnetheduck** [comment]
https://nim-lang.org/docs/system.html#new%2Ctypedesc - new takes a proc that is run whenever the gc gets to deallocating something. we could use that (probably in debug mode) to catch stragglers

**Comment by dom96** [comment]
Looks like great minds think alike :)

I implemented this: https://github.com/nim-lang/Nim/pull/11181
