### ISSUE TITLE
RFC: Transports leak tracking.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronos#32]
Implement scheme which will track create/release transports. In such way developer can find leaks in memory and OS resources (sockets or file descriptors).

## Simple way (release mode).
Maintain 2 counters, number of created transports and number of closed transports and provide procedure which can return subtraction of this two counters. In such way developer can obtain information about present leaks our double close in transports.

If there no leaking transports number of created transports must be equal to number of closed transports.

Implemented in https://github.com/status-im/nim-chronos/pull/33.

### Detailed way (debug mode).
Maintain table which will hold all the created transports and information about it
1. Remote address and port.
2. Local address and port.
3. Moment of creation (or epoch time).
4. Number of bytes sent.
5. Number of bytes received.
6. Send speed (???)
7. Receive speed (???)
8. File & line number of creation.
9. File & line number of release.

Table elements will be added when the transport is created and deleted when the transport is closed.

Provide procedure which will dump all the information from table in convenient way.

**Comment by arnetheduck** [comment]
sgtm as a stopgap solution. is there an `atexit` in nim? then we could hook it up to an assert that all transports be closed at end of program, in `strict` mode (for scripts etc, who cares)

**Comment by arnetheduck** [comment]
this also ties in with the dispatcher RFC - the natural place for such counters would be in the dispatcher to avoid even more globals - then the dispatcher becomes a dependency to create a transport - effectively, each transport is linked to its dispatcher

**Comment by cheatfate** [comment]
@arnetheduck there no globals in `chronos` dispatcher is thread-local variable.

Also dispatcher can be used without current transports, i mean it is possible to build your own transports and do not use our transports. We can even remove transports from `chronos` and put it in other repository which will depends on `chronos`. And because of that i'm thinking to add one more thread-local variable which will hold all the tracking information.

**Comment by arnetheduck** [comment]
thread-locals are globals too - they embody the same poor design, just that it's per thread.

**Comment by arnetheduck** [comment]
regarding metrics, a well-established practice is to send them out regularly to something like [graphite](https://graphiteapp.org/) (push) or prometheus (pull) which collates them - then they're forwarded to a shared database that can be plotted in grafana. I'm not sure which one we're using, but we already have most infrastructure for it. This would likely be a more long-term approach that we could use across the board, in the application. 

the approach is very simple, but it would allow us to connect the node with some very powerful monitoring tools, instead of custom-rigging it.

**Comment by cheatfate** [comment]
I dont think that `chronos` has `poor` design and i have tested/benchmark many other approaches. All of them has pros and cons, but current design is a good compromise.

Metrics are here just for proposal, and i dont think to implement it at first stage.

**Comment by dom96** [comment]
I've built a prometheus package for this exact purpose, it works very well: https://github.com/dom96/prometheus (and it supports Future tracking now)

**Comment by cheatfate** [comment]
Simple way was implemented.
