### ISSUE TITLE
chronos is not available in Nim Playground?

### ISSUE THREAD

**Issue by adokitkat** [status-im/nim-chronos#436]
> `chronos` is available in the [Nim Playground](https://play.nim-lang.org/#ix=2TpS)

This doesn't seem to be true at the moment.

I get this output for Nim v2.0 and latest:

```
Hint: used config file '/playground/nim/config/nim.cfg' [Conf]
Hint: used config file '/playground/nim/config/config.nims' [Conf]
...................................................................................................................................................Killed
```

and this output with v1.6.14:

```
Hint: used config file '/playground/nim/config/nim.cfg' [Conf]
Hint: used config file '/playground/nim/config/config.nims' [Conf]
..........................................................
/usercode/in.nim(1, 8) Error: cannot open file: chronos
```

**Comment by Menduist** [comment]
Seems like this issue belongs on the playground repo: https://github.com/PMunch/nim-playground
AFAIK, chronos is still included in the list of packages: https://github.com/PMunch/nim-playground/blob/efae1579cf9ad486fa91daf8833fbd33e001da91/docker/packages.nimble#L23

**Comment by adokitkat** [comment]
Thanks, reposted there.
