### ISSUE TITLE
Hash-order independent tests

### ISSUE THREAD

**Issue by c-blake** [status-im/nim-chronos#550]
`tests/testhttpserver.nim`(850, 12) and (852) fail with a new string hasher because they assume a specific order.

Any chance you guys can do something like @Vindaar did [here](https://github.com/SciNim/Datamancer/pull/69) in the next few days?  Really just add a `.sorted` and put the `@[]` in sorted order.

**Comment by c-blake** [comment]
Sorry - I guess the line number of the test moved from the last release to the current HEAD of this repo.  It was actually the area indicated by [this PR](https://github.com/c-blake/nim-chronos/commit/695d80ccfbb0ba34f68e630e6d8f4e686ccb37ae).

The question remains - when is the next release of chronos planned?  This error is blocking the Nim CI which is blocking a Nim-2.2 release.

**Comment by c-blake** [comment]
Also, tagging @arnetheduck since the release cadance of this repo is somewhat slow compared to my impression of what @Araq means by "imminent", since he was the last person to tag a release, and since [he said it should be merged ASAP](https://github.com/nim-lang/Nim/issues/23678#issuecomment-2175569538), ***but*** that was ambiguous between "merged under its current non-disruptive `--define=nimPreviewHashFarm`" or "merged as the new default with a define for the old murmur".

**Comment by arnetheduck** [comment]
> Sorry - I guess the line number of the test moved from the last release to the current HEAD of this repo. It was actually the area indicated by [this PR](https://github.com/c-blake/nim-chronos/commit/695d80ccfbb0ba34f68e630e6d8f4e686ccb37ae).

Can you open a PR for this? The link leads to a commit in your repo.

**Comment by c-blake** [comment]
Done.  Sorry - I actually did try to do that at first and something wasn't working then.  This is the PR cross-linked for convenience: https://github.com/status-im/nim-chronos/pull/551

**Comment by c-blake** [comment]
The mentioned PR now passes the CI and just needs to be merged.  So, I am closing this issue.
