### ISSUE TITLE
bug: epoch calculation is incorrect

### ISSUE THREAD

**Issue by AlejandroCabeza** [status-im/nim-chronos#554]
### Problem
Epoch calculation is wrong. Tested both in Fedora and WSL.

### To reproduce
```nim
import chronos
from std/times import epochTime

echo epochTime()
echo fastEpochTime()
echo Moment.now()
```

Outputs
```
1723049288.989397  # epochTime (seconds)
24664910  # fastEpochTime (milliseconds)
24664910171187ns  # Moment.now (nanoseconds)
```

### Expected behavior
Epoch calculation from chronos should be consistent with `std/times`' `epochTime()`.

### Versions
Nim: 2.0.8 and 1.6.20
Chronos: 4.0.0 and 4.0.2

**Comment by arnetheduck** [comment]
The two are entirely unrelated: https://github.com/status-im/nim-chronos/blob/dc3847e4d6733dfc3811454c2a9c384b87343e26/chronos/timer.nim#L144C1-L144C78

**Comment by AlejandroCabeza** [comment]
> The two are entirely unrelated: https://github.com/status-im/nim-chronos/blob/dc3847e4d6733dfc3811454c2a9c384b87343e26/chronos/timer.nim#L144C1-L144C78

Could you elaborate as to what's the difference?

**Comment by AlejandroCabeza** [comment]
> The two are entirely unrelated: https://github.com/status-im/nim-chronos/blob/dc3847e4d6733dfc3811454c2a9c384b87343e26/chronos/timer.nim#L144C1-L144C78

@arnetheduck Could you elaborate as to what's the difference?

**Comment by arnetheduck** [comment]
As documented, The `Moment` type represents a monotonic clock - what specific value monotonic clocks use as time source depends on os/hardware support. [As documented](https://nim-lang.org/docs/times.html#epochTime), `epochTime` in stdlib returns unix time which is not monotonic.

[Monotonic clocks](https://www.youtube.com/watch?v=i1wysckHg2o) are used to measure time differences. Unix time is also known as wall time and notably is not monotonic and therefore unsuitable for many use cases.

**Comment by AlejandroCabeza** [comment]
> As documented, The `Moment` type represents a monotonic clock - what specific value monotonic clocks use as time source depends on os/hardware support. [As documented](https://nim-lang.org/docs/times.html#epochTime), `epochTime` in stdlib returns unix time which is not monotonic.
> 
> [Monotonic clocks](https://www.youtube.com/watch?v=i1wysckHg2o) are used to measure time differences. Unix time is also known as wall time and notably is not monotonic and therefore unsuitable for many use cases.

Oh, I see. Thanks for taking the time to explain, much appreciated. I didn't know what a monotonic clock and wrongly came to a conclusion about it.
