### ISSUE TITLE
Support funcs

### ISSUE THREAD

**Issue by tersec** [status-im/nim-chronos#58]
Currently, it throws an error:
```
nim-beacon-chain/vendor/nim-chronos/chronos/asyncmacro2.nim(161, 12) Error: Cannot transform this node kind into an async proc. proc/method definition or lambda node expected.
```

**Comment by cheatfate** [comment]
@tersec `func` is procedures without side effects (this means that the proc/iterator only changes locations that are reachable from its parameters and the return value only depends on the arguments). But every {.async.} transformed procedure adding callbacks to thread-global system queue, so it exactly perform side effect. So its impossible.
