### ISSUE TITLE
write future returns wrong size if vector is fragmented

### ISSUE THREAD

**Issue by sinkingsugar** [status-im/nim-chronos#73]
https://github.com/status-im/nim-chronos/blob/e3ced62d4ba06b7ff638f6784e782046b1fadc70/chronos/transports/stream.nim#L1001
Seems to complete with just the last fragment size

Side note to @dryajov : we don't check `write` actual sent sizes, we return `Future[void]` should prob return `Future[size]`

_Originally posted by @sinkingsugar in https://github.com/status-im/nim-chronos/issues/72#issuecomment-584472636_

**Comment by dryajov** [comment]
> Side note to @dryajov : we don't check write actual sent sizes, we return Future[void] should prob return Future[size]

Good catch, yeah we should complete with the size.
