### ISSUE TITLE
Implement a secure production-ready HTTP server

### ISSUE THREAD

**Issue by zah** [status-im/nim-chronos#76]
For the purposes of implementing a [RESTful APIs](https://github.com/ethereum/eth2.0-APIs) for interacting with our [beacon node](http://github.com/status-im/nim-beacon-chain), we need a production-ready HTTP/1.1 server that integrates with nim-chronos. It should focus on strong adherence to standards with great care towards security. Additional features such as HTTPS and WebSockets will be added after the initial release.

**Comment by bung87** [comment]
I starting create a web framework build upon `chronos` ,check here https://github.com/bung87/looper if you interested

**Comment by cheatfate** [comment]
HTTP/S server is now part of `nim-chronos`.
